{
    "ROOT_QUERY":

    {
        "__typename": "Query",
 "reviews(

        { "filters": { 
            "isVerifiedPurchase": false,
 
            "prosCons": null,
 
            "starRatings": null },
 
            "itemId": "206429649",
 
            "searchTerm": null,
 
            "sortBy": "photoreview",
 
            "startIndex": 1 }
            ) " : {
                "__typename":"ReviewsResponse",

                "Results":[
                    {
                        "__typename":"ReviewModel",

                        "Rating":5,
"ReviewText":"Great purchase! Is fluffy and beautiful.Match very well with my grey sectional sofa.",

"Title":"Great purchase! Is fluffy and beautiful.Match very well with my grey sectional sofa.",

"UserNickname":"Lela",

"AuthorId":"041D6A6E5FF34DCA0S",
"Badges":{"__typename":"ReviewsBadges",
"DIY":null,
"top250Contributor":null,
"IncentivizedReview":null,
"EarlyReviewerIncentive":null,
"top1000Contributor":null,
"VerifiedPurchaser":{"__typename":"ReviewsBadge",
"BadgeType":"Custom"}},
"BadgesOrder":["VerifiedPurchaser"],
"CampaignId":"20210306_PPC_PR3_OUT_3798764",
"ContextDataValues":{"__typename":"ReviewsContextDataValues",
"Age":null,
"VerifiedPurchaser":null},
"ContextDataValuesOrder":[],
"Id":"243170881",
"IsRecommended":true,
"IsSyndicated":false,
"Photos":[{"__typename":"ReviewPhoto",
"Id":"6653826",
"Sizes":{"__typename":"ReviewPhotoSizes",
"normal":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/19c68097-9cd0-5c9f-98d0-4a3974eb40c6"},
"thumbnail":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/5b32cf7a-751d-5cb5-8a6b-7ceead19adef"}}}],
"ProductId":"206429649",
"SubmissionTime":"2021-03-07T17:44:28.000+00:00",
"TagDimensions":{"__typename":"ReviewsTagDimensions",
"Pro":null,
"Con":null},
"TotalNegativeFeedbackCount":0,
"TotalPositiveFeedbackCount":0,
"ClientResponses":[],
"RatingRange":5,
"SecondaryRatings":{"__typename":"SecondaryRatings",
"Quality":null,
"Value":null,
"EnergyEfficiency":null,
"Features":null,
"Appearance":null,
"EaseOfInstallation":null,
"EaseOfUse":null},
"SecondaryRatingsOrder":[],
"SyndicationSource":null,
"UserLocation":null,
"Videos":[]},
{"__typename":"ReviewModel",
"Rating":5,
"ReviewText":"I love this rug so much I actually bought a second identical rug for another room in my house. So yes,
 I would definitely recommend this rug!",
"Title":"I love this rug so much I actually bought a second identical rug for another room in my house. So...",
"UserNickname":"Optimistic",
"AuthorId":"051CC868B6EF781D0S",
"Badges":{"__typename":"ReviewsBadges",
"DIY":null,
"top250Contributor":null,
"IncentivizedReview":null,
"EarlyReviewerIncentive":null,
"top1000Contributor":null,
"VerifiedPurchaser":{"__typename":"ReviewsBadge",
"BadgeType":"Custom"}},
"BadgesOrder":["VerifiedPurchaser"],
"CampaignId":"20210305_PPC_PR1_ONLINE_CNTRL_3798113",
"ContextDataValues":{"__typename":"ReviewsContextDataValues",
"Age":null,
"VerifiedPurchaser":null},
"ContextDataValuesOrder":[],
"Id":"242994933",
"IsRecommended":true,
"IsSyndicated":false,
"Photos":[{"__typename":"ReviewPhoto",
"Id":"6647183",
"Sizes":{"__typename":"ReviewPhotoSizes",
"normal":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/4c2fdfdc-3026-52b4-83d4-23e19e00152e"},
"thumbnail":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/f3e10f7a-28ac-534d-9ffb-2b5ebf95136d"}}}],
"ProductId":"206873336",
"SubmissionTime":"2021-03-05T19:04:22.000+00:00",
"TagDimensions":{"__typename":"ReviewsTagDimensions",
"Pro":null,
"Con":null},
"TotalNegativeFeedbackCount":0,
"TotalPositiveFeedbackCount":0,
"ClientResponses":[],
"RatingRange":5,
"SecondaryRatings":{"__typename":"SecondaryRatings",
"Quality":null,
"Value":null,
"EnergyEfficiency":null,
"Features":null,
"Appearance":null,
"EaseOfInstallation":null,
"EaseOfUse":null},
"SecondaryRatingsOrder":[],
"SyndicationSource":null,
"UserLocation":null,
"Videos":[]},
{"__typename":"ReviewModel",
"Rating":5,
"ReviewText":"Love this rug \\r\\nvery Soft \\r\\nArrived quickly \\r\\nDurable \\r\\nGood price",
"Title":"Love this rug very Soft Arrived quickly Durable Good price",
"UserNickname":"Emily",
"AuthorId":"051B8BAB519E95EC0S",
"Badges":{"__typename":"ReviewsBadges",
"DIY":null,
"top250Contributor":null,
"IncentivizedReview":null,
"EarlyReviewerIncentive":null,
"top1000Contributor":null,
"VerifiedPurchaser":{"__typename":"ReviewsBadge",
"BadgeType":"Custom"}},
"BadgesOrder":["VerifiedPurchaser"],
"CampaignId":"20200721_PPC_PR1_ONLINE_CNTRL_3654886",
"ContextDataValues":{"__typename":"ReviewsContextDataValues",
"Age":null,
"VerifiedPurchaser":null},
"ContextDataValuesOrder":[],
"Id":"235063927",
"IsRecommended":true,
"IsSyndicated":false,
"Photos":[{"__typename":"ReviewPhoto",
"Id":"5847352",
"Sizes":{"__typename":"ReviewPhotoSizes",
"normal":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/5c064729-341f-5453-9702-a928e349a072"},
"thumbnail":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/0bcfeb5b-2f32-5616-926e-6fd645f7eabf"}}}],
"ProductId":"304267958",
"SubmissionTime":"2020-07-21T14:54:25.000+00:00",
"TagDimensions":{"__typename":"ReviewsTagDimensions",
"Pro":null,
"Con":null},
"TotalNegativeFeedbackCount":0,
"TotalPositiveFeedbackCount":1,
"ClientResponses":[],
"RatingRange":5,
"SecondaryRatings":{"__typename":"SecondaryRatings",
"Quality":null,
"Value":null,
"EnergyEfficiency":null,
"Features":null,
"Appearance":null,
"EaseOfInstallation":null,
"EaseOfUse":null},
"SecondaryRatingsOrder":[],
"SyndicationSource":null,
"UserLocation":null,
"Videos":[]},
{"__typename":"ReviewModel",
"Rating":5,
"ReviewText":"Exactly what I was looking for and you can\xe2\x80\x99t  beat the price! Looks great in my entryway from the garage.",
"Title":"Exactly what I was looking for and you can\xe2\x80\x99t ...",
"UserNickname":"HomeDepotCustomer",
"AuthorId":"03ED128A135F27900S",
"Badges":{"__typename":"ReviewsBadges",
"DIY":null,
"top250Contributor":null,
"IncentivizedReview":null,
"EarlyReviewerIncentive":null,
"top1000Contributor":null,
"VerifiedPurchaser":{"__typename":"ReviewsBadge",
"BadgeType":"Custom"}},
"BadgesOrder":["VerifiedPurchaser"],
"CampaignId":"20200609_PPC_PR1_ONLINE_CNTRL_3629566_DA_LP_Mobile",
"ContextDataValues":{"__typename":"ReviewsContextDataValues",
"Age":null,
"VerifiedPurchaser":null},
"ContextDataValuesOrder":["EarlyReviewerIncentive"],
"Id":"233291097",
"IsRecommended":null,
"IsSyndicated":false,
"Photos":[{"__typename":"ReviewPhoto",
"Id":"5707929",
"Sizes":{"__typename":"ReviewPhotoSizes",
"normal":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/51e30a87-781f-5218-a9f7-26e536bda05d"},
"thumbnail":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/51b4aa20-c667-531b-972a-944e011b0ae4"}}}],
"ProductId":"304267958",
"SubmissionTime":"2020-06-09T15:19:27.000+00:00",
"TagDimensions":{"__typename":"ReviewsTagDimensions",
"Pro":null,
"Con":null},
"TotalNegativeFeedbackCount":0,
"TotalPositiveFeedbackCount":2,
"ClientResponses":[],
"RatingRange":5,
"SecondaryRatings":{"__typename":"SecondaryRatings",
"Quality":null,
"Value":null,
"EnergyEfficiency":null,
"Features":null,
"Appearance":null,
"EaseOfInstallation":null,
"EaseOfUse":null},
"SecondaryRatingsOrder":[],
"SyndicationSource":null,
"UserLocation":null,
"Videos":[]},
{"__typename":"ReviewModel",
"Rating":4,
"ReviewText":"This rug is a loose long shag. Vacuuming is a little difficult. Price was inexpensive so this is the one I chose. Next time I\xe2\x80\x99ll spend a little more and get better quality. I gave it a 4star because if price.",
"Title":"This rug is a loose long shag. Vacuuming is a little difficult. Price was inexpensive so this is ...",
"UserNickname":"Tinker",
"AuthorId":"03ED1AFA5F2034A00S",
"Badges":{"__typename":"ReviewsBadges",
"DIY":null,
"top250Contributor":null,
"IncentivizedReview":null,
"EarlyReviewerIncentive":null,
"top1000Contributor":null,
"VerifiedPurchaser":{"__typename":"ReviewsBadge",
"BadgeType":"Custom"}},
"BadgesOrder":["VerifiedPurchaser"],
"CampaignId":"20200530_PPC_PR1_ONLINE_CNTRL_3623627",
"ContextDataValues":{"__typename":"ReviewsContextDataValues",
"Age":null,
"VerifiedPurchaser":null},
"ContextDataValuesOrder":[],
"Id":"233172707",
"IsRecommended":true,
"IsSyndicated":false,
"Photos":[{"__typename":"ReviewPhoto",
"Id":"5695373",
"Sizes":{"__typename":"ReviewPhotoSizes",
"normal":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/de75ca99-2a61-5e9f-bb8c-7d9014e6bf1f"},
"thumbnail":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/add6b098-3330-5aba-8aa0-d4698b8185ad"}}}],
"ProductId":"206429649",
"SubmissionTime":"2020-06-05T19:40:24.000+00:00",
"TagDimensions":{"__typename":"ReviewsTagDimensions",
"Pro":null,
"Con":null},
"TotalNegativeFeedbackCount":0,
"TotalPositiveFeedbackCount":1,
"ClientResponses":[],
"RatingRange":5,
"SecondaryRatings":{"__typename":"SecondaryRatings",
"Quality":null,
"Value":null,
"EnergyEfficiency":null,
"Features":null,
"Appearance":null,
"EaseOfInstallation":null,
"EaseOfUse":null},
"SecondaryRatingsOrder":[],
"SyndicationSource":null,
"UserLocation":null,
"Videos":[]},
{"__typename":"ReviewModel",
"Rating":5,
"ReviewText":"I absolutely LOVE this rug...very soft and fluffy makes my whole living room pop now and for the price this was an awesome size I mean everyone who walks in compliments it...I have a 3month old who doesn\xe2\x80\x99t mind doing tummy time on it so it\xe2\x80\x99s a WIN",
"Title":"I absolutely LOVE this rug...very soft and fluffy makes my...",
"UserNickname":"Ebony",
"AuthorId":"051AE9C4AF4E4C790S",
"Badges":{"__typename":"ReviewsBadges",
"DIY":null,
"top250Contributor":null,
"IncentivizedReview":null,
"EarlyReviewerIncentive":null,
"top1000Contributor":null,
"VerifiedPurchaser":{"__typename":"ReviewsBadge",
"BadgeType":"Custom"}},
"BadgesOrder":["VerifiedPurchaser"],
"CampaignId":"20200530_PPC_PR1_ONLINE_CNTRL_3623627_RMForm_DA_LP_Mobile",
"ContextDataValues":{"__typename":"ReviewsContextDataValues",
"Age":null,
"VerifiedPurchaser":null},
"ContextDataValuesOrder":["EarlyReviewerIncentive"],
"Id":"232666431",
"IsRecommended":null,
"IsSyndicated":false,
"Photos":[{"__typename":"ReviewPhoto",
"Id":"5665974",
"Sizes":{"__typename":"ReviewPhotoSizes",
"normal":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/5977d0a9-3cbd-5adc-9feb-d3314b7d6300"},
"thumbnail":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/bca24f7d-b3e7-5bcd-9f65-224ec22fe3ce"}}}],
"ProductId":"206429649",
"SubmissionTime":"2020-05-30T15:14:49.000+00:00",
"TagDimensions":{"__typename":"ReviewsTagDimensions",
"Pro":null,
"Con":null},
"TotalNegativeFeedbackCount":0,
"TotalPositiveFeedbackCount":1,
"ClientResponses":[],
"RatingRange":5,
"SecondaryRatings":{"__typename":"SecondaryRatings",
"Quality":null,
"Value":null,
"EnergyEfficiency":null,
"Features":null,
"Appearance":null,
"EaseOfInstallation":null,
"EaseOfUse":null},
"SecondaryRatingsOrder":[],
"SyndicationSource":null,
"UserLocation":null,
"Videos":[]},
{"__typename":"ReviewModel",
"Rating":5,
"ReviewText":"Ironically our dog just loves how plush this shag is!!! Perfect for our little guest room.",
"Title":"Ironically our dog just loves how plush this shag is!!!...",
"UserNickname":"KaysMemaw",
"AuthorId":"03ED1B09FE7725800S",
"Badges":{"__typename":"ReviewsBadges",
"DIY":null,
"top250Contributor":null,
"IncentivizedReview":null,
"EarlyReviewerIncentive":null,
"top1000Contributor":null,
"VerifiedPurchaser":{"__typename":"ReviewsBadge",
"BadgeType":"Custom"}},
"BadgesOrder":["VerifiedPurchaser"],
"CampaignId":"20200530_PPC_PR1_ONLINE_CNTRL_3623573_DA_LP_SP_Mobile",
"ContextDataValues":{"__typename":"ReviewsContextDataValues",
"Age":null,
"VerifiedPurchaser":null},
"ContextDataValuesOrder":["EarlyReviewerIncentive"],
"Id":"232663044",
"IsRecommended":null,
"IsSyndicated":false,
"Photos":[{"__typename":"ReviewPhoto",
"Id":"5665824",
"Sizes":{"__typename":"ReviewPhotoSizes",
"normal":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/7c592a84-7740-50e6-a6be-c53697d945f4"},
"thumbnail":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/bdbb51cc-a950-5252-b70c-e4d39ba7f117"}}}],
"ProductId":"310692235",
"SubmissionTime":"2020-05-30T15:03:06.000+00:00",
"TagDimensions":{"__typename":"ReviewsTagDimensions",
"Pro":null,
"Con":null},
"TotalNegativeFeedbackCount":0,
"TotalPositiveFeedbackCount":1,
"ClientResponses":[],
"RatingRange":5,
"SecondaryRatings":{"__typename":"SecondaryRatings",
"Quality":null,
"Value":null,
"EnergyEfficiency":null,
"Features":null,
"Appearance":null,
"EaseOfInstallation":null,
"EaseOfUse":null},
"SecondaryRatingsOrder":[],
"SyndicationSource":null,
"UserLocation":null,
"Videos":[]},
{"__typename":"ReviewModel",
"Rating":5,
"ReviewText":"It is a great color and very pretty design.  It holds up well with my cats and dog.  Perfect size for my entryway in my split level home.",
"Title":"It is a great color and very pretty design.  It holds up well with my cats and dog.  Perfect size...",
"UserNickname":"Homey",
"AuthorId":"031005A5454F035C0S",
"Badges":{"__typename":"ReviewsBadges",
"DIY":null,
"top250Contributor":null,
"IncentivizedReview":null,
"EarlyReviewerIncentive":null,
"top1000Contributor":null,
"VerifiedPurchaser":{"__typename":"ReviewsBadge",
"BadgeType":"Custom"}},
"BadgesOrder":["VerifiedPurchaser"],
"CampaignId":"20200407_PPC_PR2_IN_ONLINE_CNTRL_3593525",
"ContextDataValues":{"__typename":"ReviewsContextDataValues",
"Age":null,
"VerifiedPurchaser":null},
"ContextDataValuesOrder":[],
"Id":"230804854",
"IsRecommended":true,
"IsSyndicated":false,
"Photos":[{"__typename":"ReviewPhoto",
"Id":"5521564",
"Sizes":{"__typename":"ReviewPhotoSizes",
"normal":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/0456bd4a-b469-5395-a4f4-714b0c19b6d4"},
"thumbnail":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/55c0bb70-f2df-5db0-bf51-b5457dfd8c56"}}}],
"ProductId":"206429637",
"SubmissionTime":"2020-04-08T16:48:56.000+00:00",
"TagDimensions":{"__typename":"ReviewsTagDimensions",
"Pro":null,
"Con":null},
"TotalNegativeFeedbackCount":0,
"TotalPositiveFeedbackCount":1,
"ClientResponses":[],
"RatingRange":5,
"SecondaryRatings":{"__typename":"SecondaryRatings",
"Quality":null,
"Value":null,
"EnergyEfficiency":null,
"Features":null,
"Appearance":null,
"EaseOfInstallation":null,
"EaseOfUse":null},
"SecondaryRatingsOrder":[],
"SyndicationSource":null,
"UserLocation":null,
"Videos":[]},
{"__typename":"ReviewModel",
"Rating":5,
"ReviewText":"Exceeds our expectations. Thickness,
 design and colors perfect for our dining room.  Quality plus. Lays flat to the floor without any additional under gripper. Ordered additional runner for my kitchen. Online purchase site unseen lower priced.  Couldn\'t be happier.  Brought my dining room to life for the holidays.",
"Title":"Exceeds our expectations. Thickness,
 design and colors perfect for our dining room.  Quality plus...",
"UserNickname":"Nunnie",
"AuthorId":"03ED1CB15C3724F00S",
"Badges":{"__typename":"ReviewsBadges",
"DIY":null,
"top250Contributor":null,
"IncentivizedReview":null,
"EarlyReviewerIncentive":null,
"top1000Contributor":null,
"VerifiedPurchaser":{"__typename":"ReviewsBadge",
"BadgeType":"Custom"}},
"BadgesOrder":["VerifiedPurchaser"],
"CampaignId":"20191231_PPC_PR1_ONLINE_CNTRL_3529055",
"ContextDataValues":{"__typename":"ReviewsContextDataValues",
"Age":null,
"VerifiedPurchaser":null},
"ContextDataValuesOrder":[],
"Id":"227866300",
"IsRecommended":true,
"IsSyndicated":false,
"Photos":[{"__typename":"ReviewPhoto",
"Id":"5309595",
"Sizes":{"__typename":"ReviewPhotoSizes",
"normal":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/0874675b-8bfa-551b-839e-570ecf9b96af"},
"thumbnail":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/d84e5c06-e769-538c-ba91-c997f863316d"}}}],
"ProductId":"206429649",
"SubmissionTime":"2019-12-31T14:53:45.000+00:00",
"TagDimensions":{"__typename":"ReviewsTagDimensions",
"Pro":null,
"Con":null},
"TotalNegativeFeedbackCount":0,
"TotalPositiveFeedbackCount":2,
"ClientResponses":[],
"RatingRange":5,
"SecondaryRatings":{"__typename":"SecondaryRatings",
"Quality":null,
"Value":null,
"EnergyEfficiency":null,
"Features":null,
"Appearance":null,
"EaseOfInstallation":null,
"EaseOfUse":null},
"SecondaryRatingsOrder":[],
"SyndicationSource":null,
"UserLocation":null,
"Videos":[]},
{"__typename":"ReviewModel",
"Rating":5,
"ReviewText":"A beautiful plush rug for a reasonable price.",
"Title":"A beautiful plush rug for a reasonable price.",
"UserNickname":"Doll",
"AuthorId":"0517E028CCD2B26B0S",
"Badges":{"__typename":"ReviewsBadges",
"DIY":null,
"top250Contributor":null,
"IncentivizedReview":null,
"EarlyReviewerIncentive":null,
"top1000Contributor":null,
"VerifiedPurchaser":{"__typename":"ReviewsBadge",
"BadgeType":"Custom"}},
"BadgesOrder":["VerifiedPurchaser"],
"CampaignId":"20191105_PPC_PR1_ONLINE_TEST_3490011",
"ContextDataValues":{"__typename":"ReviewsContextDataValues",
"Age":null,
"VerifiedPurchaser":null},
"ContextDataValuesOrder":[],
"Id":"225884303",
"IsRecommended":true,
"IsSyndicated":false,
"Photos":[{"__typename":"ReviewPhoto",
"Id":"5200079",
"Sizes":{"__typename":"ReviewPhotoSizes",
"normal":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/360af227-94f3-521d-90f3-71c32a5da5ea"},
"thumbnail":{"__typename":"ReviewPhotoSize",
"Url":"https://photos-us.bazaarvoice.com/photo/2/cGhvdG86aG9tZWRlcG90/9d0b0997-f415-534f-9501-90c9c0842842"}}}],
"ProductId":"206429649",
"SubmissionTime":"2019-11-05T15:23:16.000+00:00",
"TagDimensions":{"__typename":"ReviewsTagDimensions",
"Pro":null,
"Con":null},
"TotalNegativeFeedbackCount":0,
"TotalPositiveFeedbackCount":2,
"ClientResponses":[],
"RatingRange":5,
"SecondaryRatings":{"__typename":"SecondaryRatings",
"Quality":null,
"Value":null,
"EnergyEfficiency":null,
"Features":null,
"Appearance":null,
"EaseOfInstallation":null,
"EaseOfUse":null},
"SecondaryRatingsOrder":[],
"SyndicationSource":null,
"UserLocation":null,
"Videos":[]}],
"Includes":{"__typename":"ReviewIncludes",
"Products":{"__typename":"ReviewIncludesProducts",
"items":[{"__typename":"ReviewProductDataStore",
"FilteredReviewStatistics":{"__typename":"ReviewsFilteredReviewStatistics",
"AverageOverallRating":"4.665520206362855",
"TotalReviewCount":1163,
"RecommendedCount":274,
"NotRecommendedCount":17,
"SecondaryRatingsAveragesOrder":["Appearance",
"EaseOfInstallation",
"Quality",
"Value"],
"RatingDistribution":[{"__typename":"RatingDistribution",
"RatingValue":5,
"Count":926},
{"__typename":"RatingDistribution",
"RatingValue":4,
"Count":159},
{"__typename":"RatingDistribution",
"RatingValue":3,
"Count":30},
{"__typename":"RatingDistribution",
"RatingValue":1,
"Count":26},
{"__typename":"RatingDistribution",
"RatingValue":2,
"Count":22}],
"ContextDataDistribution":{"__typename":"ContextDataDistributions",
"Age":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"25to34"},
{"__typename":"ContextDataDistributionValue",
"Value":"55to64"},
{"__typename":"ContextDataDistributionValue",
"Value":"65orOver"}]},
"Gender":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"Male"},
{"__typename":"ContextDataDistributionValue",
"Value":"Female"}]},
"Expertise":null,
"VerifiedPurchaser":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"True",
"Count":"1062"},
{"__typename":"ContextDataDistributionValue",
"Value":"False",
"Count":"68"}]}}},
"Id":"310692235"},
{"__typename":"ReviewProductDataStore",
"FilteredReviewStatistics":{"__typename":"ReviewsFilteredReviewStatistics",
"AverageOverallRating":"4.665520206362855",
"TotalReviewCount":1163,
"RecommendedCount":274,
"NotRecommendedCount":17,
"SecondaryRatingsAveragesOrder":["Appearance",
"EaseOfInstallation",
"Quality",
"Value"],
"RatingDistribution":[{"__typename":"RatingDistribution",
"RatingValue":5,
"Count":926},
{"__typename":"RatingDistribution",
"RatingValue":4,
"Count":159},
{"__typename":"RatingDistribution",
"RatingValue":3,
"Count":30},
{"__typename":"RatingDistribution",
"RatingValue":1,
"Count":26},
{"__typename":"RatingDistribution",
"RatingValue":2,
"Count":22}],
"ContextDataDistribution":{"__typename":"ContextDataDistributions",
"Age":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"25to34"},
{"__typename":"ContextDataDistributionValue",
"Value":"55to64"},
{"__typename":"ContextDataDistributionValue",
"Value":"65orOver"}]},
"Gender":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"Male"},
{"__typename":"ContextDataDistributionValue",
"Value":"Female"}]},
"Expertise":null,
"VerifiedPurchaser":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"True",
"Count":"1062"},
{"__typename":"ContextDataDistributionValue",
"Value":"False",
"Count":"68"}]}}},
"Id":"304267958"},
{"__typename":"ReviewProductDataStore",
"FilteredReviewStatistics":{"__typename":"ReviewsFilteredReviewStatistics",
"AverageOverallRating":"4.665520206362855",
"TotalReviewCount":1163,
"RecommendedCount":274,
"NotRecommendedCount":17,
"SecondaryRatingsAveragesOrder":["Appearance",
"EaseOfInstallation",
"Quality",
"Value"],
"RatingDistribution":[{"__typename":"RatingDistribution",
"RatingValue":5,
"Count":926},
{"__typename":"RatingDistribution",
"RatingValue":4,
"Count":159},
{"__typename":"RatingDistribution",
"RatingValue":3,
"Count":30},
{"__typename":"RatingDistribution",
"RatingValue":1,
"Count":26},
{"__typename":"RatingDistribution",
"RatingValue":2,
"Count":22}],
"ContextDataDistribution":{"__typename":"ContextDataDistributions",
"Age":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"25to34"},
{"__typename":"ContextDataDistributionValue",
"Value":"55to64"},
{"__typename":"ContextDataDistributionValue",
"Value":"65orOver"}]},
"Gender":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"Male"},
{"__typename":"ContextDataDistributionValue",
"Value":"Female"}]},
"Expertise":null,
"VerifiedPurchaser":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"True",
"Count":"1062"},
{"__typename":"ContextDataDistributionValue",
"Value":"False",
"Count":"68"}]}}},
"Id":"206429637"},
{"__typename":"ReviewProductDataStore",
"FilteredReviewStatistics":{"__typename":"ReviewsFilteredReviewStatistics",
"AverageOverallRating":"4.665520206362855",
"TotalReviewCount":1163,
"RecommendedCount":274,
"NotRecommendedCount":17,
"SecondaryRatingsAveragesOrder":["Appearance",
"EaseOfInstallation",
"Quality",
"Value"],
"RatingDistribution":[{"__typename":"RatingDistribution",
"RatingValue":5,
"Count":926},
{"__typename":"RatingDistribution",
"RatingValue":4,
"Count":159},
{"__typename":"RatingDistribution",
"RatingValue":3,
"Count":30},
{"__typename":"RatingDistribution",
"RatingValue":1,
"Count":26},
{"__typename":"RatingDistribution",
"RatingValue":2,
"Count":22}],
"ContextDataDistribution":{"__typename":"ContextDataDistributions",
"Age":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"25to34"},
{"__typename":"ContextDataDistributionValue",
"Value":"55to64"},
{"__typename":"ContextDataDistributionValue",
"Value":"65orOver"}]},
"Gender":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"Male"},
{"__typename":"ContextDataDistributionValue",
"Value":"Female"}]},
"Expertise":null,
"VerifiedPurchaser":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"True",
"Count":"1062"},
{"__typename":"ContextDataDistributionValue",
"Value":"False",
"Count":"68"}]}}},
"Id":"206873336"}],
"store":{"__typename":"ReviewProductDataStore",
"FilteredReviewStatistics":{"__typename":"ReviewsFilteredReviewStatistics",
"AverageOverallRating":"4.7",
"TotalReviewCount":1163,
"RecommendedCount":274,
"NotRecommendedCount":17,
"SecondaryRatingsAveragesOrder":["Appearance",
"EaseOfInstallation",
"Quality",
"Value"],
"RatingDistribution":[{"__typename":"RatingDistribution",
"RatingValue":5,
"Count":926},
{"__typename":"RatingDistribution",
"RatingValue":4,
"Count":159},
{"__typename":"RatingDistribution",
"RatingValue":3,
"Count":30},
{"__typename":"RatingDistribution",
"RatingValue":2,
"Count":22},
{"__typename":"RatingDistribution",
"RatingValue":1,
"Count":26}],
"ContextDataDistribution":{"__typename":"ContextDataDistributions",
"Age":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"18to24"},
{"__typename":"ContextDataDistributionValue",
"Value":"25to34"},
{"__typename":"ContextDataDistributionValue",
"Value":"35to44"},
{"__typename":"ContextDataDistributionValue",
"Value":"45to54"},
{"__typename":"ContextDataDistributionValue",
"Value":"55to64"},
{"__typename":"ContextDataDistributionValue",
"Value":"65orOver"}]},
"Gender":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"Male"},
{"__typename":"ContextDataDistributionValue",
"Value":"Female"}]},
"Expertise":null,
"VerifiedPurchaser":{"__typename":"ContextDataDistribution",
"Values":[{"__typename":"ContextDataDistributionValue",
"Value":"True",
"Count":"1062"},
{"__typename":"ContextDataDistributionValue",
"Value":"False",
"Count":"68"}]}}},
"Id":"206429649"}}},
"TotalResults":1163,
"FilterSelected":{"__typename":"BVReviewFilter",
"StarRatings":null,
"VerifiedPurchaser":null,
"SearchText":null},
"pagination":{"__typename":"BVPagination",
"previousPage":null,
"pages":[{"__typename":"BVPage",
"label":"1",
"isNextPage":null,
"isPreviousPage":null,
"isSelectedPage":true},
{"__typename":"BVPage",
"label":"2",
"isNextPage":null,
"isPreviousPage":null,
"isSelectedPage":false},
{"__typename":"BVPage",
"label":null,
"isNextPage":null,
"isPreviousPage":null,
"isSelectedPage":false},
{"__typename":"BVPage",
"label":"117",
"isNextPage":null,
"isPreviousPage":null,
"isSelectedPage":false}],
"nextPage":{"__typename":"BVPage",
"label":"2",
"isNextPage":true,
"isPreviousPage":null,
"isSelectedPage":false}},
"SortBy":{"__typename":"BVSortBy",
"mosthelpfull":null,
"newest":null,
"oldest":null,
"highestrating":null,
"lowestrating":null,
"photoreview":true}},
"questionsAnswers({"itemId":"206429649"})":{"__typename":"QAResponse",
"TotalResults":46,
"Includes":{"__typename":"Includes",
"Answers":[{"__typename":"AnswerIncludes",
"AnswerId":"10692323",
"Answer":{"__typename":"Answer",
"Id":"10692323",
"AnswerText":"No,
 Ivory is an off-white color,
 not as white as white,
 but not as dark as off-white."}},
{"__typename":"AnswerIncludes",
"AnswerId":"11061392",
"Answer":{"__typename":"Answer",
"Id":"11061392",
"AnswerText":"Yes."}},
{"__typename":"AnswerIncludes",
"AnswerId":"10750567",
"Answer":{"__typename":"Answer",
"Id":"10750567",
"AnswerText":"I wouldn\xe2\x80\x99t machine wash it. Would guess it would weaken integrity of backing."}},
{"__typename":"AnswerIncludes",
"AnswerId":"11061397",
"Answer":{"__typename":"Answer",
"Id":"11061397",
"AnswerText":"Yes"}},
{"__typename":"AnswerIncludes",
"AnswerId":"8988707",
"Answer":{"__typename":"Answer",
"Id":"8988707",
"AnswerText":"It\'s only available to buy online and will ship to your address"}},
{"__typename":"AnswerIncludes",
"AnswerId":"8590828",
"Answer":{"__typename":"Answer",
"Id":"8590828",
"AnswerText":"Yes,
 it is washable."}},
{"__typename":"AnswerIncludes",
"AnswerId":"9794891",
"Answer":{"__typename":"Answer",
"Id":"9794891",
"AnswerText":"Yes,
 this rug can vacuum easily"}},
{"__typename":"AnswerIncludes",
"AnswerId":"10732381",
"Answer":{"__typename":"Answer",
"Id":"10732381",
"AnswerText":"No,
 this is more of a dark vanilla color,
 like cream colored."}},
{"__typename":"AnswerIncludes",
"AnswerId":"8764698",
"Answer":{"__typename":"Answer",
"Id":"8764698",
"AnswerText":"It is grayish."}},
{"__typename":"AnswerIncludes",
"AnswerId":"10162551",
"Answer":{"__typename":"Answer",
"Id":"10162551",
"AnswerText":"Yes it vacuums easily its really great once its settled after being rolled up for delivery its a dream so soft and easy to maintain my family loves this rug"}},
{"__typename":"AnswerIncludes",
"AnswerId":"10033787",
"Answer":{"__typename":"Answer",
"Id":"10033787",
"AnswerText":"Fast delivery and great quality. Very soft."}},
{"__typename":"AnswerIncludes",
"AnswerId":"9046097",
"Answer":{"__typename":"Answer",
"Id":"9046097",
"AnswerText":"This can\'t be used for stairs."}},
{"__typename":"AnswerIncludes",
"AnswerId":"8592201",
"Answer":{"__typename":"Answer",
"Id":"8592201",
"AnswerText":"Hello,
,
\\n\\nOnly spot cleaning and/or hand wash for cleaning."}},
{"__typename":"AnswerIncludes",
"AnswerId":"10572674",
"Answer":{"__typename":"Answer",
"Id":"10572674",
"AnswerText":"No,
 I had mine for  years now and I\'m very happy with it.\\r\\nIt\'s hard to vacuum it at first since it\'s on a thick side but overall we love it."}},
{"__typename":"AnswerIncludes",
"AnswerId":"10692340",
"Answer":{"__typename":"Answer",
"Id":"10692340",
"AnswerText":"No,
 our rugs are only spot cleanable. Putting them in the washing machine may cause problems and unnecessary wear."}},
{"__typename":"AnswerIncludes",
"AnswerId":"10588026",
"Answer":{"__typename":"Answer",
"Id":"10588026",
"AnswerText":"No it does not. Great rug."}},
{"__typename":"AnswerIncludes",
"AnswerId":"10141605",
"Answer":{"__typename":"Answer",
"Id":"10141605",
"AnswerText":"Yes."}},
{"__typename":"AnswerIncludes",
"AnswerId":"9061234",
"Answer":{"__typename":"Answer",
"Id":"9061234",
"AnswerText":"No,
 it is not recommended to be machine washed."}},
{"__typename":"AnswerIncludes",
"AnswerId":"9174880",
"Answer":{"__typename":"Answer",
"Id":"9174880",
"AnswerText":"Unfortunately,
 we currently do not have this item available in a 6\'7" x 9\'3" size like our other shag rugs. If we bring this size in however,
 it will be uploaded to Home Depot when it arrives. At the moment though,
 we only have the sizes currently available on site."}},
{"__typename":"AnswerIncludes",
"AnswerId":"10920226",
"Answer":{"__typename":"Answer",
"Id":"10920226",
"AnswerText":"Yes,
 I have no problem vacuuming it."}}],
"AnswersOrder":["10732381",
"10692323",
"10692340",
"10588026",
"10572674",
"11061397",
"11061392",
"10920226",
"10162551",
"10141605",
"9794891",
"10750567",
"9061234",
"9046097",
"9174880",
"10033787",
"8988707",
"8764698",
"8592201",
"8590828"]},
"Limit":10,
"Offset":0,
"Results":[{"__typename":"QAModel",
"AnswerIds":["10732381",
"10692323"],
"QuestionSummary":"Is ivory brown?",
"SubmissionTime":"2020-12-18T06:35:46.000+00:00",
"UserNickname":"Ozzie"},
{"__typename":"QAModel",
"AnswerIds":["10692340"],
"QuestionSummary":"Can I put the 3x5 rug in the washing machine on gentle and let it air dry?",
"SubmissionTime":"2020-12-17T03:15:06.000+00:00",
"UserNickname":"EK"},
{"__typename":"QAModel",
"AnswerIds":["10588026",
"10572674"],
"QuestionSummary":"Does it shed?",
"SubmissionTime":"2020-11-23T20:15:28.000+00:00",
"UserNickname":"kkeo"},
{"__typename":"QAModel",
"AnswerIds":["11061397",
"11061392",
"10920226",
"10162551",
"10141605",
"9794891"],
"QuestionSummary":"Does this rug vacuum easily?",
"SubmissionTime":"2020-05-25T16:52:32.000+00:00",
"UserNickname":"Lou"},
{"__typename":"QAModel",
"AnswerIds":["10750567",
"9061234"],
"QuestionSummary":"Can these be machine washed?",
"SubmissionTime":"2019-12-18T14:45:49.000+00:00",
"UserNickname":"Tauni"},
{"__typename":"QAModel",
"AnswerIds":["9046097"],
"QuestionSummary":"Can this be used for stairs?",
"SubmissionTime":"2019-12-14T23:14:54.000+00:00",
"UserNickname":"Jb"},
{"__typename":"QAModel",
"AnswerIds":["9174880"],
"QuestionSummary":"I want this rug 6,
7 x 9,
3",
"SubmissionTime":"2019-12-14T15:50:22.000+00:00",
"UserNickname":"Maria"},
{"__typename":"QAModel",
"AnswerIds":["10033787",
"8988707"],
"QuestionSummary":"Can I pick it up on Saturday",
"SubmissionTime":"2019-11-28T14:21:19.000+00:00",
"UserNickname":"Heather"},
{"__typename":"QAModel",
"AnswerIds":["8764698"],
"QuestionSummary":"I have been eyeing this rug now for a week,
 is it more blueish or greyish?",
"SubmissionTime":"2019-10-03T02:40:14.000+00:00",
"UserNickname":"annabanana"},
{"__typename":"QAModel",
"AnswerIds":["8592201",
"8590828"],
"QuestionSummary":"Is it washable?",
"SubmissionTime":"2019-08-25T14:05:11.000+00:00",
"UserNickname":"Ann"}]},
"product:{"itemId":"206429649"}":{"__ref":"base-catalog-206429649"}},
"base-catalog-206429649":{"__typename":"BaseProduct",
"itemId":"206429649",
"dataSources":"catalog",
"identifiers":{"__typename":"Identifiers",
"canonicalUrl":"/p/Ottomanson-Ultimate-Shag-Contemporary-Moroccan-Grey-8-ft-x-10-ft-Trellis-Area-Rug-SHG2273-8X10/206429649",
"brandName":"Ottomanson",
"itemId":"206429649",
"modelNumber":"SHG2273-8X10",
"productLabel":"Ultimate Shag Contemporary Moroccan Grey 8 ft. x 10 ft. Trellis Area Rug",
"storeSkuNumber":null,
"upcGtin13":"0849928028495",
"specialOrderSku":null,
"toolRentalSkuNumber":null,
"rentalCategory":null,
"rentalSubCategory":null,
"upc":"849928028495",
"productType":"MERCHANDISE",
"isSuperSku":true,
"parentId":"316528709"},
"availabilityType":{"__typename":"AvailabilityType",
"discontinued":false,
"status":true,
"type":"Shared"},
"details":{"__typename":"Details",
"description":"Fill your room with warmth and style by choosing the Ottomanson Ultimate Shaggy Contemporary Moroccan Trellis Design 8 ft. x 10 ft. Area Rug. This area rug features stain-resistant fabrics and has fade-resistant materials. It comes in a gray shade,
 bringing a subdued touch to any decor. With a 100% polypropylene construction,
 this rug is an extremely durable option for your home. It has a shag texture,
 which adds a soft and fluffy feel that will bring unbeatable comfort and coziness to any space. This rug provides a plush surface to walk on,
 boasting a lavish appearance to your flooring.",
"collection":null,
"highlights":["Shag texture for a fluffy touch",
"Fade-resistant materials keep it looking new",
"1.97 in. pile feels luxurious and soft"],
"descriptiveAttributes":[{"__typename":"DescriptiveAttribute",
"name":"Bullet01",
"value":"Stain-resistant construction allows it to tolerate everyday drips and spills",
"bulleted":true,
"sequence":0},
{"__typename":"DescriptiveAttribute",
"name":"Bullet02",
"value":"Jute backing prevents the rug from moving",
"bulleted":true,
"sequence":0},
{"__typename":"DescriptiveAttribute",
"name":"Bullet03",
"value":"Gray color is a sensible choice,
 pairing well with your other decor",
"bulleted":true,
"sequence":0},
{"__typename":"DescriptiveAttribute",
"name":"Bullet04",
"value":"Plush pile for a soft and comfortable feel underfoot",
"bulleted":true,
"sequence":0},
{"__typename":"DescriptiveAttribute",
"name":"Bullet05",
"value":"Loomed for a spectacular finish",
"bulleted":true,
"sequence":0},
{"__typename":"DescriptiveAttribute",
"name":"Bullet06",
"value":"Measures 1.97 in. in thickness",
"bulleted":true,
"sequence":0},
{"__typename":"DescriptiveAttribute",
"name":"Bullet07",
"value":"Actual Dimensions: 9 ft. 10 in. x 7 ft. 10 in.",
"bulleted":true,
"sequence":0},
{"__typename":"DescriptiveAttribute",
"name":"Bullet09",
"value":"Please note: The digital images and product dimensions on our website are as accurate as possible. Due to differences in computer monitors,
 some rug colors may vary slightly. Lengths and widths may vary from the published dimensions. We do our best to provide you with an exact measurement,
 but please be advised that some variation exists. Patterns may vary slightly according to shape and size selected.",
"bulleted":true,
"sequence":0},
{"__typename":"DescriptiveAttribute",
"name":"Bullet19",
"value":"\\u003ca href="https://www.homedepot.com/c/ai/rug-sizes-for-your-space/9ba683603be9fa5395fab901838423fe" target="_blank" style="color:#F96302;">Choose the best area rug size for every room in your home\\u003c/a>",
"bulleted":true,
"sequence":0},
{"__typename":"DescriptiveAttribute",
"name":"Bullet20",
"value":"\\u003ca href="https://www.homedepot.com/c/ah/how-to-clean-a-rug/9ba683603be9fa5395fab901ca51b169" target="_blank" style="color:#F96302;">Learn how to clean and maintain your area rug\\u003c/a>",
"bulleted":true,
"sequence":0}],
"infoAndGuides":[{"__typename":"InfoAndGuides",
"name":"Warranty",
"url":"https://images.thdstatic.com/catalog/pdfImages/7f/7fde8be3-46ca-433f-87ff-a6f377c22ee0.pdf"},
{"__typename":"InfoAndGuides",
"name":"Use and Care Manual",
"url":"https://images.thdstatic.com/catalog/pdfImages/5c/5c903ae4-117c-4e97-beed-8f7179422431.pdf"}]},
"media":{"__typename":"Media",
"images":[{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/19bc4511-240b-4a60-8359-14fd7cbde7bf/svn/gray-ottomanson-area-rugs-shg2273-8x10-64_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE",
"subType":"PRIMARY"},
{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/d74a83d9-f213-45d1-8d83-461487b9ad29/svn/gray-ottomanson-area-rugs-shg2273-8x10-e1_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE_LEFT_VIEW",
"subType":null},
{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/85264b50-e8ed-4992-8d11-fc56b6a1ab42/svn/gray-ottomanson-area-rugs-shg2273-8x10-40_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE_RIGHT_VIEW",
"subType":null},
{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/d5184a57-a2a0-4990-b6b0-0cb7cb34f796/svn/gray-ottomanson-area-rugs-shg2273-8x10-a0_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE_TOP_VIEW",
"subType":null},
{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/d8c9d955-c134-40e7-8ede-c27dc54ad332/svn/gray-ottomanson-area-rugs-shg2273-8x10-1d_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE_BOTTOM_VIEW",
"subType":null},
{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/91bdea74-e890-4b48-a233-422887eb8b7a/svn/gray-ottomanson-area-rugs-shg2273-8x10-66_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE_BACK_VIEW",
"subType":null},
{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/ba13a0de-6428-4398-9204-69c22117a668/svn/gray-ottomanson-area-rugs-shg2273-8x10-77_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE_OPEN_VIEW",
"subType":null},
{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/bfad00b5-b17a-41ac-84df-4de58f836adf/svn/gray-ottomanson-area-rugs-shg2273-8x10-c3_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE_ALTERNATE_VIEW",
"subType":null},
{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/bb00a48f-e69e-454d-9005-f080bf10a7a4/svn/gray-ottomanson-area-rugs-shg2273-8x10-4f_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE_ALTERNATE_VIEW_2",
"subType":null},
{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/367197eb-d1ef-4a73-9e6c-242fa3313e8a/svn/gray-ottomanson-area-rugs-shg2273-8x10-1f_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE_ALTERNATE_VIEW_3",
"subType":null},
{"__typename":"Image",
"url":"https://images.thdstatic.com/productImages/5ab1ef2a-bd9b-4a9c-aac2-99c70362e72e/svn/gray-ottomanson-area-rugs-shg2273-8x10-44_\\u003cSIZE>.jpg",
"sizes":["65",
"100",
"145",
"300",
"400",
"600",
"1000"],
"type":"IMAGE_ALTERNATE_VIEW_4",
"subType":null}],
"video":[{"__typename":"Video",
"shortDescription":"For a unique and cozy accessory to your home decor,
 the Ultimate Shaggy Contemporary Moroccan Trellis Design Gray Area Rug is a great selection.\\n",
"thumbnail":"https://cf-images.us-east-1.prod.boltdns.net/v1/static/1834613806001/fa45e92a-2b6d-484b-b41f-283c5e5861b1/af5359ff-7a61-4f6c-aa39-c037504de14d/160x90/match/image.jpg?pubId=66036796001",
"url":"https://bcbolt446c5271-a.akamaihd.net/media/v1/pmp4/static/clear/1834613806001/fa45e92a-2b6d-484b-b41f-283c5e5861b1/b008730f-565a-445a-baeb-cc1015be2e31/main.mp4?akamai_token=exp=1622798531~acl=/media/v1/pmp4/static/clear/1834613806001/fa45e92a-2b6d-484b-b41f-283c5e5861b1/b008730f-565a-445a-baeb-cc1015be2e31/main.mp4*~hmac=61d03cae6aff81fc6c8aa1bb333c9dc90926c0a09bd50abe9ec7ff4d0f005f7e&pubid=66036796001",
"videoStill":"https://cf-images.us-east-1.prod.boltdns.net/v1/static/1834613806001/fa45e92a-2b6d-484b-b41f-283c5e5861b1/ee7bcd44-d882-4779-b6b1-8266394d673e/1280x720/match/image.jpg?pubId=66036796001",
"link":null,
"title":"Ottomanson Ultimate Area Rug",
"type":"BRIGHTCOVE VIDEO",
"videoId":"5828341702001",
"longDescription":null},
{"__typename":"Video",
"shortDescription":"For a unique and cozy accessory to your home decor,
 the Ultimate Shaggy Contemporary Moroccan Trellis Design Gray Area Rug is a great selection.\\n",
"thumbnail":"https://cf-images.us-east-1.prod.boltdns.net/v1/static/1834613806001/fa45e92a-2b6d-484b-b41f-283c5e5861b1/af5359ff-7a61-4f6c-aa39-c037504de14d/160x90/match/image.jpg?pubId=66036796001",
"url":"https://bcbolt446c5271-a.akamaihd.net/media/v1/pmp4/static/clear/1834613806001/fa45e92a-2b6d-484b-b41f-283c5e5861b1/b008730f-565a-445a-baeb-cc1015be2e31/main.mp4?akamai_token=exp=1622798531~acl=/media/v1/pmp4/static/clear/1834613806001/fa45e92a-2b6d-484b-b41f-283c5e5861b1/b008730f-565a-445a-baeb-cc1015be2e31/main.mp4*~hmac=61d03cae6aff81fc6c8aa1bb333c9dc90926c0a09bd50abe9ec7ff4d0f005f7e&pubid=66036796001",
"videoStill":"https://cf-images.us-east-1.prod.boltdns.net/v1/static/1834613806001/fa45e92a-2b6d-484b-b41f-283c5e5861b1/ee7bcd44-d882-4779-b6b1-8266394d673e/1280x720/match/image.jpg?pubId=66036796001",
"link":null,
"title":"Ottomanson Ultimate Area Rug",
"type":"BRIGHTCOVE SUPPLEMENT 1",
"videoId":"5828341702001",
"longDescription":null}],
"threeSixty":null,
"augmentedRealityLink":{"__typename":"AugmentedRealityLink",
"usdz":["206429649_5f4523856efc736adc95ce930214c44a.usdz"],
"image":null},
"richContent":null},
"pricing({"storeId":"8119"})":{"__typename":"Pricing",
"promotion":{"__typename":"Promotion",
"dates":{"__typename":"Dates",
"end":"05/09/2021",
"start":"04/29/2021"},
"type":"DISCOUNT",
"description":null,
"dollarOff":13.15,
"percentageOff":10,
"savingsCenter":"Special Buys",
"savingsCenterPromos":null,
"specialBuySavings":null,
"specialBuyDollarOff":null,
"specialBuyPercentageOff":null},
"value":118.34,
"alternatePriceDisplay":false,
"alternate":{"__typename":"Alternate",
"bulk":null,
"unit":{"__typename":"UnitPricing",
"caseUnitOfMeasure":null,
"unitsOriginalPrice":null,
"unitsPerCase":null,
"value":null}},
"original":131.49,
"mapAboveOriginalPrice":null,
"message":null,
"preferredPriceFlag":false,
"specialBuy":null,
"unitOfMeasure":"each"},
"reviews":{"__typename":"Reviews",
"ratingsReviews":{"__typename":"RatingsReviews",
"averageRating":"4.6655",
"totalReviews":"1163"}},
"seo":{"__typename":"Seo",
"seoKeywords":null,
"seoDescription":"Bring inspired style to your living room with this amazing Ottomanson Ultimate Shag Contemporary Moroccan Trellis Design Grey Area Rug. Convenient to handle."},
"specificationGroup":[{"__typename":"SpecificationGroup",
"specifications":[{"__typename":"Specification",
"specName":"Features",
"specValue":"Stain Resistant"},
{"__typename":"Specification",
"specName":"Style",
"specValue":"Mediterranean,
Modern"},
{"__typename":"Specification",
"specName":"Weave Type",
"specValue":"Loomed"},
{"__typename":"Specification",
"specName":"Origin",
"specValue":"Imported"},
{"__typename":"Specification",
"specName":"Pattern",
"specValue":"Trellis"},
{"__typename":"Specification",
"specName":"Shade Type",
"specValue":"Light"},
{"__typename":"Specification",
"specName":"Construction",
"specValue":"Machine-Made"},
{"__typename":"Specification",
"specName":"Returnable",
"specValue":"30-Day"},
{"__typename":"Specification",
"specName":"Rug Weight (lbs.)",
"specValue":"42.9"},
{"__typename":"Specification",
"specName":"Material",
"specValue":"Polypropylene (100%)"},
{"__typename":"Specification",
"specName":"Theme",
"specValue":"Unthemed"},
{"__typename":"Specification",
"specName":"Location Type",
"specValue":"Bathroom,
Bedroom,
Classroom,
Dining Room,
Entryway,
Kids Bedroom,
Kitchen,
Laundry Room,
Living Room,
Nursery,
Office,
Playroom"},
{"__typename":"Specification",
"specName":"Recycled Materials (%)",
"specValue":"0"},
{"__typename":"Specification",
"specName":"Cleaning Instructions",
"specValue":"Spot clean"},
{"__typename":"Specification",
"specName":"Shape",
"specValue":"Rectangle"},
{"__typename":"Specification",
"specName":"Color Family",
"specValue":"Gray"},
{"__typename":"Specification",
"specName":"Color/Finish",
"specValue":"Gray"},
{"__typename":"Specification",
"specName":"Indoor/Outdoor",
"specValue":"Indoor"},
{"__typename":"Specification",
"specName":"Flooring Product Type",
"specValue":"Area Rug"},
{"__typename":"Specification",
"specName":"Rug Material",
"specValue":"Jute,
Polypropylene"},
{"__typename":"Specification",
"specName":"Backing Material",
"specValue":"Jute"}],
"specTitle":"Details"},
{"__typename":"SpecificationGroup",
"specifications":[{"__typename":"Specification",
"specName":"Manufacturer Warranty",
"specValue":"30 day Manufacturer Warranty for damages and defects only."}],
"specTitle":"Warranty / Certifications"},
{"__typename":"SpecificationGroup",
"specifications":[{"__typename":"Specification",
"specName":"Product Length (in.)",
"specValue":"118"},
{"__typename":"Specification",
"specName":"Coverage Area (sq. ft)",
"specValue":"80"},
{"__typename":"Specification",
"specName":"Pile Height (in.)",
"specValue":"1.2"},
{"__typename":"Specification",
"specName":"Product Thickness (in.)",
"specValue":"1.2"},
{"__typename":"Specification",
"specName":"Shape,
 Exact W x L",
"specValue":"Rectangle,
 7\'10" x 9\'10""},
{"__typename":"Specification",
"specName":"Product Width (in.)",
"specValue":"94 in"}],
"specTitle":"Dimensions"}],
"taxonomy":{"__typename":"Taxonomy",
"breadCrumbs":[{"__typename":"BreadCrumb",
"label":"Flooring",
"url":"/b/Flooring/N-5yc1vZaq7r",
"browseUrl":null,
"creativeIconUrl":null,
"deselectUrl":null,
"dimensionName":"Category",
"refinementKey":null},
{"__typename":"BreadCrumb",
"label":"Rugs",
"url":"/b/Flooring-Rugs/N-5yc1vZarfm",
"browseUrl":null,
"creativeIconUrl":null,
"deselectUrl":null,
"dimensionName":"Category",
"refinementKey":null},
{"__typename":"BreadCrumb",
"label":"Area Rugs",
"url":"/b/Flooring-Rugs-Area-Rugs/N-5yc1vZarjg",
"browseUrl":null,
"creativeIconUrl":null,
"deselectUrl":null,
"dimensionName":"Category",
"refinementKey":null}],
"brandLinkUrl":"/b/Flooring-Rugs-Area-Rugs/Ottomanson/N-5yc1vZevkZarjg"},
"info":{"__typename":"Info",
"hidePrice":false,
"ecoRebate":false,
"quantityLimit":0,
"sskMin":null,
"sskMax":null,
"unitOfMeasureCoverage":null,
"wasMaxPriceRange":null,
"wasMinPriceRange":null,
"fiscalYear":"2021",
"productDepartment":"23",
"classNumber":"3",
"label":null,
"prop65Warning":false,
"returnable":"30-Day",
"globalCustomConfigurator":null},
"sizeAndFitDetail":{"__typename":"SizeAndFitDetail",
"attributeGroups":[{"__typename":"sizeAndFitAttributeGroup",
"attributes":[{"__typename":"sizeAndFitAttribute",
"attributeName":null,
"dimensions":"118 x 94"}],
"dimensionLabel":"L x W (in.)",
"productType":null}]},
"keyProductFeatures":{"__typename":"KeyProductFeatures",
"keyProductFeaturesItems":[{"__typename":"KeyProductFeaturesItem",
"features":[{"__typename":"KeyProductFeaturesFeature",
"name":"Shape",
"refinementId":"4294966861",
"refinementUrl":"/b/Flooring-Rugs-Area-Rugs/Rectangle/N-5yc1vZarjgZ1z141n1",
"value":"Rectangle"},
{"__typename":"KeyProductFeaturesFeature",
"name":"Style",
"refinementId":"4294029804",
"refinementUrl":"/b/Flooring-Rugs-Area-Rugs/Modern/N-5yc1vZarjgZ1z0jylo",
"value":"Modern"},
{"__typename":"KeyProductFeaturesFeature",
"name":"Features",
"refinementId":"4294421411",
"refinementUrl":"/b/Flooring-Rugs-Area-Rugs/Stain-Resistant/N-5yc1vZarjgZ1z0scrn",
"value":"Stain Resistant"},
{"__typename":"KeyProductFeaturesFeature",
"name":"Weave Type",
"refinementId":"4295161669",
"refinementUrl":"/b/Flooring-Rugs-Area-Rugs/Loomed/N-5yc1vZarjgZ1z187yd",
"value":"Loomed"},
{"__typename":"KeyProductFeaturesFeature",
"name":"Rug Material",
"refinementId":"4295160778",
"refinementUrl":"/b/Flooring-Rugs-Area-Rugs/Jute/N-5yc1vZarjgZ1z1879m",
"value":"Jute"},
{"__typename":"KeyProductFeaturesFeature",
"name":"Construction",
"refinementId":"4295161272",
"refinementUrl":"/b/Flooring-Rugs-Area-Rugs/Machine-Made/N-5yc1vZarjgZ1z187nc",
"value":"Machine-Made"},
{"__typename":"KeyProductFeaturesFeature",
"name":"Rug Material",
"refinementId":"4295160867",
"refinementUrl":"/b/Flooring-Rugs-Area-Rugs/Polypropylene/N-5yc1vZarjgZ1z187c3",
"value":"Polypropylene"},
{"__typename":"KeyProductFeaturesFeature",
"name":"Flooring Product Type",
"refinementId":"4294595911",
"refinementUrl":"/b/Flooring-Rugs-Area-Rugs/Area-Rug/N-5yc1vZarjgZ1z0w3ev",
"value":"Area Rug"}]}]}}}